import { GoogleSpreadsheet } from 'google-spreadsheet';
import { google } from 'googleapis';
import { JWT } from 'google-auth-library';


/*
Service Account angular_backend
  angular-backend@adorn4711test.iam.gserviceaccount.com


  Excample sheet: https://docs.google.com/spreadsheets/d/1QpNG99Pnm_Sfz2Wle1deEnkne5Wi-49sUTy_Xu_xXqI/edit?gid=0#gid=0
*/
import creds from '../key/adorn4711test-a51513af553d.json'; // the file saved above
// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: creds.client_email,
  key: creds.private_key,
  scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
});


console.log('creds', creds);
const sheets = google.sheets({ version: 'v4', auth: serviceAccountAuth });
const spreadsheetId = '1QpNG99Pnm_Sfz2Wle1deEnkne5Wi-49sUTy_Xu_xXqI';

// const res = await sheets.spreadsheets.get({ spreadsheetId });
//  console.log('Title:', res.data.properties?.title);

const doc = new GoogleSpreadsheet('1QpNG99Pnm_Sfz2Wle1deEnkne5Wi-49sUTy_Xu_xXqI', serviceAccountAuth);

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
//await doc.updateProperties({ title: 'renamed doc' });

const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
console.log(sheet.title);
console.log(sheet.rowCount);
